### ISSUE TITLE
How to get all values in cache?

### ISSUE THREAD

**Issue by LMS5413** [eluneevermore/ioredis-cache#1]
Im using this package and i have a doubt. How to get all values saved in cache?

**Comment by eluneevermore** [comment]
This package doesn't have any function to get all cached value at the moment. You have to use redis commands.

If you are using the `cache` command, you may want to use a [prefix](https://github.com/redis/ioredis?tab=readme-ov-file#transparent-key-prefixing) for your cache:
`const cache = new Cache(new Redis({ keyPrefix: "foo:" }))`
Then either use `cache.redis.keys` or `cache.redis.scan` to get all keys with your prefix, then use them as argument for `cache.getManyCache`.

If you are using the `hashCache` command, you can use `cache.redis.hgetall` and parse the cached values by yourself.

Btw, I wonder why do you need to get cached values without knowing their keys?
